CREATE SCHEMA IF NOT EXISTS `urlshortner` DEFAULT CHARACTER SET utf8 ;
use `urlshortner`;

DROP TABLE  IF EXISTS `urlshortner`.`URL_TRACKER`;
DROP TABLE  IF EXISTS `urlshortner`.`URL_IDENTIFIER`;

CREATE TABLE IF NOT EXISTS `urlshortner`.`URL_IDENTIFIER` (
  `URL_ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `CREATED_DATETIME` TIMESTAMP NOT NULL,
  PRIMARY KEY (`URL_ID`)
)
ENGINE = InnoDB AUTO_INCREMENT=1000;


CREATE  TABLE IF NOT EXISTS `urlshortner`.`URL_TRACKER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `URL_ID` BIGINT(20) NOT NULL ,
  `ORIGINAL_URL` VARCHAR(1000) NOT NULL ,
  `SHORT_URL` VARCHAR(100) NOT NULL ,
  `CREATED_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `ACCESSED_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ON UPDATE CURRENT_TIMESTAMP,
  `COUNTER` INT,
  PRIMARY KEY (`ID`) ,
  INDEX `url_idr_fk_idx` (`URL_ID` ASC),
  CONSTRAINT `url_fk`
    FOREIGN KEY (`URL_ID`)
    REFERENCES `urlshortner`.`URL_IDENTIFIER` (`URL_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
